export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_FAILURE = 'SEARCH_REQUEST_FAILURE';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';

export const SEARCH_FORM_UI_QUERY = 'SEARCH_FORM_UI_QUERY';
export const SEARCH_FORM_UI_STYLE = 'SEARCH_FORM_UI_STYLE';
export const SEARCH_FORM_UI_ORIENTATION = 'SEARCH_FORM_UI_ORIENTATION';
export const SEARCH_FORM_UI_SOURCES = 'SEARCH_FORM_UI_SOURCES';

export const GET_REQUEST = 'GET_REQUEST';
export const GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE';
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS';
